# Render Blueprint: one-click deploy for Microshop
services:
  # Public gateway: serves UI + proxies /api/*
  - type: web
    name: microshop-gateway
    env: docker
    plan: free
    autoDeploy: true
    rootDir: gateway
    dockerfilePath: ./gateway/Dockerfile
    healthCheckPath: /

  # Private product service
  - type: private_service
    name: product-service
    env: docker
    plan: free
    autoDeploy: true
    rootDir: product-service
    dockerfilePath: ./product-service/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microshop-product-db
          property: connectionString
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:8000

  # Private user service
  - type: private_service
    name: user-service
    env: docker
    plan: free
    autoDeploy: true
    rootDir: user-service
    dockerfilePath: ./user-service/Dockerfile
    healthCheckPath: /
    envVars:
      - key: USER_SERVICE_URL
        value: http://user-service:8001

  # Private order service
  - type: private_service
    name: order-service
    env: docker
    plan: free
    autoDeploy: true
    rootDir: order-service
    dockerfilePath: ./order-service/Dockerfile
    healthCheckPath: /
    envVars:
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:8000

  # Private payment service
  - type: private_service
    name: payment-service
    env: docker
    plan: free
    autoDeploy: true
    rootDir: payment-service
    dockerfilePath: ./payment-service/Dockerfile
    healthCheckPath: /

databases:
  - name: microshop-product-db
    plan: free
