# Render Blueprint: one-click deploy for Microshop (all-free, public backends)
services:
  - type: web
    name: microshop-gateway
    runtime: docker
    plan: free
    autoDeploy: true
    rootDir: gateway
    dockerfilePath: ./gateway/Dockerfile
    healthCheckPath: /

  - type: web
    name: product-service
    runtime: docker
    plan: free
    autoDeploy: true
    rootDir: product-service
    dockerfilePath: ./product-service/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microshop-product-db
          property: connectionString

  - type: web
    name: user-service
    runtime: docker
    plan: free
    autoDeploy: true
    rootDir: user-service
    dockerfilePath: ./user-service/Dockerfile
    healthCheckPath: /

  - type: web
    name: order-service
    runtime: docker
    plan: free
    autoDeploy: true
    rootDir: order-service
    dockerfilePath: ./order-service/Dockerfile
    healthCheckPath: /
    envVars:
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:8000

  - type: web
    name: payment-service
    runtime: docker
    plan: free
    autoDeploy: true
    rootDir: payment-service
    dockerfilePath: ./payment-service/Dockerfile
    healthCheckPath: /

databases:
  - name: microshop-product-db
    plan: free
